export const APP_REGISTRY = {
  doom: {
    title: "DOOM — js-dos",
    glyph: "D00M",
    category: "Games",
    description: "The classic desktop break, running in the local js-dos wrapper.",
    keywords: ["doom", "dos", "js-dos", "game"],
    size: [690, 565],
  },
  games: {
    title: "Games",
    glyph: "GAME",
    category: "Games",
    description: "All workstation games in one folder.",
    keywords: ["games", "arcade", "break"],
    size: [760, 600],
  },
  utilities: {
    title: "Utilities",
    glyph: "UTIL",
    category: "System",
    description: "Scratchpad, calculator, camera, paint, and system utilities.",
    keywords: ["utilities", "calculator", "camera", "paint"],
    size: [780, 620],
  },
  flash: {
    title: "Flash Files",
    glyph: "SWF",
    category: "Media",
    description: "Badger Badger Badger, Ruffle, and third-party attributions.",
    keywords: ["flash", "swf", "badger", "ruffle"],
    size: [720, 570],
  },
  router: {
    title: "Support Router",
    glyph: "PY",
    category: "Support",
    description: "Route customer issues and prepare a human-reviewed reply.",
    keywords: ["support", "router", "python", "agents", "reply"],
    size: [780, 660],
  },
  tools: {
    title: "Support Tools",
    glyph: "SLA",
    category: "Support",
    description: "Timers, request IDs, retry backoff, and status-code guidance.",
    keywords: ["support", "sla", "request id", "backoff", "status"],
    size: [710, 610],
  },
  files: {
    title: "Public",
    glyph: "DIR",
    category: "System",
    description: "Apps, source, tests, README, downloads, and project notes.",
    keywords: ["files", "folder", "public", "downloads"],
    size: [760, 590],
  },
  terminal: {
    title: "Terminal",
    glyph: ">_",
    category: "System",
    description: "Immediate shell with real CPython and the Agents SDK prewarmed.",
    keywords: ["terminal", "command prompt", "shell", "python", "xterm"],
    size: [820, 560],
  },
  about: {
    title: "About me",
    glyph: "RW",
    category: "Ryan",
    description: "Profile card, selected work, and field notes.",
    keywords: ["ryan", "about", "profile", "ryanw.eu"],
    size: [780, 630],
  },
  work: {
    title: "Selected Work",
    glyph: "LAB",
    category: "Ryan",
    description: "Current systems and public projects.",
    keywords: ["work", "projects", "portfolio"],
    size: [760, 600],
  },
  notes: {
    title: "PROCESS.md",
    glyph: "MD",
    category: "Ryan",
    description: "Decisions, boundaries, and interview notes.",
    keywords: ["process", "markdown", "decisions", "interview"],
    size: [620, 650],
  },
  help: {
    title: "Help & UX Review",
    glyph: "?",
    category: "System",
    description: "Shortcuts, safeguards, Nielsen review, and accessibility notes.",
    keywords: ["help", "shortcuts", "nielsen", "accessibility"],
    size: [720, 600],
  },
  browser: {
    title: "Browser",
    glyph: "WEB",
    category: "Internet",
    description: "Browse same-origin resources and open external sites safely.",
    keywords: ["browser", "web", "internet", "url"],
    size: [820, 610],
  },
  devtools: {
    title: "DevTools",
    glyph: "DEV",
    category: "System",
    description: "Inspect runtime, network, storage, performance, and console state.",
    keywords: ["developer", "devtools", "console", "network", "performance"],
    size: [760, 560],
  },
  monaco: {
    title: "Monaco Editor",
    glyph: "M",
    category: "Productivity",
    description: "VS Code’s editor for the shipped Python, Markdown, JSON, and web files.",
    keywords: ["monaco", "code", "editor", "vscode", "python"],
    size: [860, 640],
  },
  tinymce: {
    title: "TinyMCE",
    glyph: "T",
    category: "Productivity",
    description: "Rich-text editor with HTML export.",
    keywords: ["tinymce", "rich text", "wysiwyg", "document"],
    size: [820, 620],
  },
  pdf: {
    title: "PDF",
    glyph: "PDF",
    category: "Productivity",
    description: "Open, zoom, print, and download local PDF files.",
    keywords: ["pdf", "document", "print", "viewer"],
    size: [780, 640],
  },
  marked: {
    title: "Marked",
    glyph: "MD",
    category: "Productivity",
    description: "Preview local Markdown safely.",
    keywords: ["marked", "markdown", "preview", "readme"],
    size: [760, 610],
  },
  paint: {
    title: "Paint",
    glyph: "PNT",
    category: "Graphics",
    description: "Create and export a drawing in the browser.",
    keywords: ["paint", "draw", "image", "canvas"],
    size: [760, 590],
  },
  photos: {
    title: "Photos",
    glyph: "IMG",
    category: "Graphics",
    description: "Open local images with fit and zoom controls.",
    keywords: ["photos", "image", "viewer", "pictures"],
    size: [760, 590],
  },
  opentype: {
    title: "OpenType",
    glyph: "Aa",
    category: "Graphics",
    description: "Load a local font and inspect it with sample text.",
    keywords: ["font", "opentype", "ttf", "otf", "woff"],
    size: [720, 560],
  },
  video: {
    title: "Video Player",
    glyph: "VID",
    category: "Media",
    description: "Play local audio and video files.",
    keywords: ["video", "audio", "media", "player"],
    size: [780, 580],
  },
  webamp: {
    title: "Webamp",
    glyph: "♫",
    category: "Media",
    description: "Winamp-inspired audio player with local-file support.",
    keywords: ["webamp", "winamp", "music", "audio"],
    size: [520, 480],
  },
  ruffle: {
    title: "Ruffle",
    glyph: "RF",
    category: "Media",
    description: "Flash content player for local SWF files.",
    keywords: ["ruffle", "flash", "swf"],
    size: [720, 570],
  },
  irc: {
    title: "IRC",
    glyph: "IRC",
    category: "Internet",
    description: "Open the KiwiIRC web client in an isolated window.",
    keywords: ["irc", "chat", "kiwiirc", "internet"],
    size: [800, 590],
  },
  messenger: {
    title: "Messenger",
    glyph: "MSG",
    category: "Internet",
    description: "Local-only support message scratch space; nothing is transmitted.",
    keywords: ["messenger", "chat", "message", "support"],
    size: [600, 590],
  },
  chess: {
    title: "Chess",
    glyph: "♞",
    category: "Games",
    description: "A local two-player chess board.",
    keywords: ["chess", "board", "game"],
    size: [600, 650],
  },
  classicube: {
    title: "ClassiCube",
    glyph: "C3D",
    category: "Games",
    description: "The browser ClassiCube client.",
    keywords: ["classicube", "minecraft", "game", "3d"],
    size: [760, 560],
  },
  dxball: {
    title: "DX-Ball",
    glyph: "DX",
    category: "Games",
    description: "Block-breaker arcade game.",
    keywords: ["dx ball", "arkanoid", "breakout", "game"],
    size: [720, 570],
  },
  spacecadet: {
    title: "Space Cadet Pinball",
    glyph: "PIN",
    category: "Games",
    description: "Browser port of the classic pinball table.",
    keywords: ["space cadet", "pinball", "game"],
    size: [780, 620],
  },
  quake3: {
    title: "Quake III Arena",
    glyph: "Q3",
    category: "Games",
    description: "Browser Quake III client.",
    keywords: ["quake", "fps", "arena", "game"],
    size: [800, 620],
  },
  emulator: {
    title: "EmulatorJS",
    glyph: "EMU",
    category: "Emulation",
    description: "Load a legally owned ROM into EmulatorJS.",
    keywords: ["emulator", "rom", "console", "game"],
    size: [800, 610],
  },
  tic80: {
    title: "TIC-80",
    glyph: "T80",
    category: "Emulation",
    description: "Fantasy-console player and editor.",
    keywords: ["tic80", "fantasy console", "game"],
    size: [760, 590],
  },
  v86: {
    title: "Virtual x86",
    glyph: "x86",
    category: "Emulation",
    description: "Start a browser-based x86 virtual machine from your own image.",
    keywords: ["v86", "virtual machine", "iso", "x86"],
    size: [820, 630],
  },
  boxedwine: {
    title: "BoxedWine",
    glyph: "EXE",
    category: "Emulation",
    description: "Run supported 16/32-bit Windows applications in the browser.",
    keywords: ["boxedwine", "windows", "exe", "emulator"],
    size: [760, 580],
  },
  stable: {
    title: "Stable Diffusion",
    glyph: "SD",
    category: "Graphics",
    description: "Open a local-capable image-generation workspace.",
    keywords: ["stable diffusion", "image generation", "webgpu"],
    size: [780, 600],
  },
  vim: {
    title: "Vim",
    glyph: "VIM",
    category: "Productivity",
    description: "Keyboard-first text editing with familiar Vim commands.",
    keywords: ["vim", "editor", "text", "code"],
    size: [760, 580],
  },
} as const satisfies Record<
  string,
  {
    title: string;
    glyph: string;
    category: string;
    description: string;
    keywords: readonly string[];
    size: readonly [number, number];
  }
>;

export type AppId = keyof typeof APP_REGISTRY;
export type AppCategory = (typeof APP_REGISTRY)[AppId]["category"];

export const APP_IDS = Object.keys(APP_REGISTRY) as AppId[];
export const APP_CATEGORIES = [
  "Support",
  "Productivity",
  "Internet",
  "Graphics",
  "Media",
  "Games",
  "Emulation",
  "System",
  "Ryan",
] as const;

export const TASKBAR_PINNED: AppId[] = ["files", "terminal", "router", "monaco"];
